language: python
sudo: required
dist: xenial

python:
  - "2.7"
  - "3.6"
  - "3.7"

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE test_db;'

env:
  - DJANGO_VERSION=1.8
  - DJANGO_VERSION=1.10
  - DJANGO_VERSION=1.11
  - DJANGO_VERSION=2.0
  - DJANGO_VERSION=2.1
  - DJANGO_VERSION=2.2

matrix:
  exclude:
    - python: "2.7"
      env: DJANGO_VERSION=2.0
    - python: "2.7"
      env: DJANGO_VERSION=2.1
    - python: "2.7"
      env: DJANGO_VERSION=2.2
    - python: "3.7"
      env: DJANGO_VERSION=1.11

install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install mysqlclient

script:
  - python manage.py test
